### PR TITLE
Adjust Linux bootstrap: Musl compat and no implicit GCC assumption

### PR DESCRIPTION
**Pull request by vazub**
- Don't assume GCC by default, prefer giving user an option of setting CC env variable with Make invocation. 
- Define -D_LARGEFILE64_SOURCE, for better compat with Musl, as per https://wiki.musl-libc.org/faq

### CODE REVIEW

**Comment by vazub** [comment]
Ah, it just occurred to me, that since I suggested to change the example in README, it implicitly means other .mk files need to be adjusted as well, if this example is to be valid. Or, adjusting the readme, to specifically mention that CC invocation works for linux-x64 version only.

**Comment by Oldes** [comment]
It should be noted, that this branch is only to make a bootstrap version, it is not preferred way to build Rebol! But it is true, that I should improve the Siskin Builder tool to be able override settings like which compiler to use without need to modify the configuration (nest) files.

**Comment by Oldes** [comment]
Any idea how to make it the most user friendly?

**Comment by Oldes** [comment]
Also I'm not sure how useful is the `_LARGEFILE64_SOURCE` define... Rebol is limited to 32bit series! I'm not sure if I want to enlarge it, because it would also enhance memory usage. And to be honest, I never needed it... although it could be needed later as I start playing with video, where large files are expected... on the other side, one don't want to load complete video into a memory, so still no need to have 64bit series addressing.

**Pull request merged**
